// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE0xcXmUZpf5hFVutesOJgdCeCj15KV3M',
    appId: '1:912557353742:web:0cf1882f57f5fb4cfe055f',
    messagingSenderId: '912557353742',
    projectId: 'com-example-divyastotram-9e6b6',
    authDomain: 'com-example-divyastotram-9e6b6.firebaseapp.com',
    storageBucket: 'com-example-divyastotram-9e6b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpyLhWsl03Wo9MpXhq72Twn6P5g8gqRcU',
    appId: '1:912557353742:android:325794c2f03b84c3fe055f',
    messagingSenderId: '912557353742',
    projectId: 'com-example-divyastotram-9e6b6',
    storageBucket: 'com-example-divyastotram-9e6b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt_kxm12PYVDDZbAowqXhsgbRneexrJ2M',
    appId: '1:912557353742:ios:2dd5a28a14478a2afe055f',
    messagingSenderId: '912557353742',
    projectId: 'com-example-divyastotram-9e6b6',
    storageBucket: 'com-example-divyastotram-9e6b6.firebasestorage.app',
    iosBundleId: 'com.bhakti.bhakti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt_kxm12PYVDDZbAowqXhsgbRneexrJ2M',
    appId: '1:912557353742:ios:2dd5a28a14478a2afe055f',
    messagingSenderId: '912557353742',
    projectId: 'com-example-divyastotram-9e6b6',
    storageBucket: 'com-example-divyastotram-9e6b6.firebasestorage.app',
    iosBundleId: 'com.bhakti.bhakti',
  );
}
