/// Comprehensive localized dictionary for Bhakti App
/// Supports: Kannada (kn), English (en), Hindi (hi), Tamil (ta), Malayalam (ml)
class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      // App Branding & General
      'appName': 'Bhakti',
      'appTagline': 'Divine Music for a Better Life',
      'spiritualTagline': 'Spirituality for Everyone, Everywhere',
      'heroSpiritualQuote': 'Let divine music fill your heart with peace and joy',
      'universalPrayer': '॥ May all beings everywhere be happy and free ॥',
      
      // Navigation
      'navHome': 'Home',
      'navSongs': 'Library',
      'navFavorites': 'Favorites',
      'navSettings': 'Settings',
      'navSearch': 'Search',
      
      // Home Sections
      'recentlyPlayed': 'Recently Played',
      'popularDevotionals': 'Popular Devotionals',
      'recommended': 'Recommended for You',
      'browseByLanguage': 'Browse by Language',
      'browseByCategory': 'Categories',
      'browseByDeity': 'Sacred Deities',
      'viewAll': 'View All',
      'playAll': 'Play All',
      'clearAll': 'Clear All',
      
      // Language Selection Screen
      'selectLanguage': 'Select Language',
      'selectLanguageSubtitle': 'One App • Many Divine Languages • Same Devotion',
      'continueButton': 'Continue',
      'kannada': 'Kannada',
      'english': 'English',
      'hindi': 'Hindi',
      'tamil': 'Tamil',
      'malayalam': 'Malayalam',
      
      // Search
      'searchPlaceholder': 'Search stotras, bhajans, deities...',
      'searchHint': 'Type Lalitha, Hanuman, Shiva, Vishnu...',
      'noSearchResults': 'No devotional songs found matching your search.',
      'recentSearches': 'Recent Searches',
      
      // Song Details & Library
      'songs': 'Devotional Songs',
      'allSongs': 'All Songs',
      'filterBy': 'Filter by',
      'lyrics': 'Sacred Lyrics',
      'noLyricsAvailable': 'Sacred lyrics will be available soon.',
      'deity': 'Deity',
      'category': 'Category',
      'duration': 'Duration',
      'artist': 'Artist / Tradition',
      
      // Player Controls
      'play': 'Play',
      'pause': 'Pause',
      'previous': 'Previous',
      'next': 'Next',
      'seekForward15': 'Forward 15s',
      'seekBackward15': 'Backward 15s',
      'speed': 'Speed',
      'sleepTimer': 'Sleep Timer',
      'queue': 'Queue',
      'favorite': 'Favorite',
      'unfavorite': 'Unfavorite',
      'addedToFavorites': 'Added to Favorites',
      'removedFromFavorites': 'Removed from Favorites',
      'repeatOff': 'Repeat Off',
      'repeatAll': 'Repeat All',
      'repeatOne': 'Repeat One',
      'shuffle': 'Shuffle',
      'nowPlaying': 'Now Playing',
      'upNext': 'Up Next',
      'clearQueue': 'Clear Queue',
      'queueEmpty': 'Your playback queue is empty.',
      
      // Sleep Timer
      'timerOff': 'Timer Off',
      'min15': '15 minutes',
      'min30': '30 minutes',
      'min45': '45 minutes',
      'min60': '60 minutes',
      'endOfSong': 'End of current song',
      'timerSetFor': 'Sleep timer set for',
      'timerCancelled': 'Sleep timer cancelled',

      // Favorites & Recents
      'noFavoritesTitle': 'No Favorites Yet',
      'noFavoritesSubtitle': 'Tap the heart icon on any devotional song to keep it in your sacred collection.',
      'noRecentsTitle': 'No Recently Played Songs',
      'noRecentsSubtitle': 'Your sacred listening history will appear here.',
      
      // Settings
      'settingsTitle': 'Settings & Preferences',
      'languageSetting': 'App Language',
      'themeSetting': 'Theme & Appearance',
      'playbackSetting': 'Audio & Playback Quality',
      'clearCache': 'Clear Cached Media',
      'cacheSize': 'Approximate Cached Media',
      'clearCacheConfirm': 'Cached audio and images will be cleared. Continue?',
      'cacheCleared': 'Cached media cleared successfully.',
      'clearRecents': 'Clear Recently Played History',
      'recentsCleared': 'Listening history cleared.',
      'aboutBhakti': 'About Bhakti App',
      'privacyPolicy': 'Privacy Policy',
      'termsOfService': 'Terms of Service',
      'contactSupport': 'Contact & Feedback',
      'adminPortal': 'Admin Portal',
      'version': 'Version',
      
      // Admin Portal
      'adminLogin': 'Administrator Login',
      'adminLoginSubtitle': 'Manage and publish devotional songs globally',
      'username': 'Username / Email',
      'password': 'Password',
      'login': 'Login',
      'logout': 'Logout',
      'invalidCredentials': 'Invalid administrator credentials. Please try again.',
      'adminDashboard': 'Admin Dashboard',
      'totalSongs': 'Total Songs',
      'publishedSongs': 'Published',
      'draftSongs': 'Drafts',
      'categories': 'Categories',
      'addSong': '+ Add New Song',
      'editSong': 'Edit Devotional Song',
      'deleteSong': 'Delete Song',
      'deleteConfirm': 'Are you sure you want to delete this devotional song? This action cannot be undone.',
      'publish': 'Publish Globally',
      'saveDraft': 'Save as Draft',
      'songTitle': 'Song Title',
      'selectLanguageField': 'Select Language',
      'selectCategoryField': 'Select Category',
      'deityField': 'Deity Name',
      'descriptionField': 'Description / Significance',
      'artistField': 'Artist / Singer / Composer',
      'albumField': 'Album / Collection',
      'lyricsField': 'Sacred Lyrics (Optional)',
      'uploadImage': 'Select Artwork / Cover (JPG/WebP)',
      'uploadAudio': 'Select Audio File (MP3/M4A)',
      'imageSelected': 'Image Selected',
      'audioSelected': 'Audio Selected',
      'publishingInProgress': 'Uploading media and publishing globally...',
      'songSavedSuccess': 'Devotional song published successfully to all users!',
      'manageCategories': 'Manage Categories',
      'syncSampleContent': 'Seed / Sync Sample Content to Cloud',

      // Errors & State
      'noInternet': 'No internet connection. Cached devotionals are available.',
      'errorLoadingSongs': 'Unable to load devotional songs. Please try again.',
      'errorPlayingAudio': 'Unable to play this audio stream. Please check connection.',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'save': 'Save',
    },

    'kn': {
      // App Branding & General
      'appName': 'ಭಕ್ತಿ',
      'appTagline': 'ಉತ್ತಮ ಜೀವನಕ್ಕಾಗಿ ದಿವ್ಯ ಸಂಗೀತ',
      'spiritualTagline': 'ಎಲ್ಲರಿಗೂ, ಎಲ್ಲೆಡೆಯೂ ಆಧ್ಯಾತ್ಮಿಕತೆ',
      'heroSpiritualQuote': 'ದಿವ್ಯ ಸಂಗೀತವು ನಿಮ್ಮ ಹೃದಯವನ್ನು ಶಾಂತಿ ಮತ್ತು ಭಕ್ತಿಯಿಂದ ತುಂಬಲಿ',
      'universalPrayer': '॥ ಲೋಕಾಃ ಸಮಸ್ತಾಃ ಸುಖಿನೋ ಭವಂತು ॥',
      
      // Navigation
      'navHome': 'ಮುಖಪುಟ',
      'navSongs': 'ಹಾಡುಗಳು',
      'navFavorites': 'ಮೆಚ್ಚಿನವು',
      'navSettings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'navSearch': 'ಹುಡುಕಿ',
      
      // Home Sections
      'recentlyPlayed': 'ಇತ್ತೀಚೆಗೆ ನುಡಿಸಿದವು',
      'popularDevotionals': 'ಜನಪ್ರಿಯ ಭಕ್ತಿಗೀತೆಗಳು',
      'recommended': 'ನಿಮಗಾಗಿ ಆಯ್ದವು',
      'browseByLanguage': 'ಭಾಷೆಯ ಮೂಲಕ ಬ್ರೌಸ್ ಮಾಡಿ',
      'browseByCategory': 'ವರ್ಗಗಳು',
      'browseByDeity': 'ದೇವರ ಸ್ತೋತ್ರಗಳು',
      'viewAll': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'playAll': 'ಎಲ್ಲಾ ಪ್ಲೇ ಮಾಡಿ',
      'clearAll': 'ಎಲ್ಲ ತೆರವುಗೊಳಿಸಿ',
      
      // Language Selection Screen
      'selectLanguage': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'selectLanguageSubtitle': 'ಒಂದೇ ಆಪ್ • ಅನೇಕ ಭಾಷೆಗಳು • ಒಂದೇ ಭಕ್ತಿ',
      'continueButton': 'ಮುಂದುವರಿಯಿರಿ',
      'kannada': 'ಕನ್ನಡ',
      'english': 'English',
      'hindi': 'हिन्दी',
      'tamil': 'தமிழ்',
      'malayalam': 'മലയാളം',
      
      // Search
      'searchPlaceholder': 'ಸ್ತೋತ್ರಗಳು, ಭಜನೆಗಳು, ದೇವರ ಹೆಸರು ಹುಡುಕಿ...',
      'searchHint': 'ಲಲಿತಾ, ಹನುಮಾನ್, ಶಿವ, ವಿಷ್ಣು...',
      'noSearchResults': 'ಯಾವುದೇ ಭಕ್ತಿಗೀತೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
      'recentSearches': 'ಇತ್ತೀಚಿನ ಹುಡುಕಾಟಗಳು',
      
      // Song Details & Library
      'songs': 'ಭಕ್ತಿಗೀತೆಗಳು',
      'allSongs': 'ಎಲ್ಲಾ ಹಾಡುಗಳು',
      'filterBy': 'ಫಿಲ್ಟರ್ ಮಾಡಿ',
      'lyrics': 'ಸಾಹಿತ್ಯ',
      'noLyricsAvailable': 'ಸಾಹಿತ್ಯ ಶೀಘ್ರದಲ್ಲೇ ಲಭ್ಯವಾಗಲಿದೆ.',
      'deity': 'ದೇವರು',
      'category': 'ವರ್ಗ',
      'duration': 'ಅವಧಿ',
      'artist': 'ಹಾಡಿದವರು / ರಚನೆ',
      
      // Player Controls
      'play': 'ಪ್ಲೇ',
      'pause': 'ವಿರಾಮ',
      'previous': 'ಹಿಂದಿನದು',
      'next': 'ಮುಂದಿನದು',
      'seekForward15': 'ಮುಂದಕ್ಕೆ ೧೫ ಸೆ',
      'seekBackward15': 'ಹಿಂದಕ್ಕೆ ೧೫ ಸೆ',
      'speed': 'ವೇಗ',
      'sleepTimer': 'ಸ್ಲೀಪ್ ಟೈಮರ್',
      'queue': 'ಸರತಿ ಸಾಲು',
      'favorite': 'ಮೆಚ್ಚಿನವು',
      'unfavorite': 'ತೆಗೆದುಹಾಕಿ',
      'addedToFavorites': 'ಮೆಚ್ಚಿನವುಗಳಿಗೆ ಸೇರಿಸಲಾಗಿದೆ',
      'removedFromFavorites': 'ಮೆಚ್ಚಿನವುಗಳಿಂದ ತೆಗೆದುಹಾಕಲಾಗಿದೆ',
      'repeatOff': 'ಪುನರಾವರ್ತನೆ ಆಫ್',
      'repeatAll': 'ಎಲ್ಲವನ್ನೂ ಪುನರಾವರ್ತಿಸಿ',
      'repeatOne': 'ಒಂದನ್ನು ಪುನರಾವರ್ತಿಸಿ',
      'shuffle': 'ಶಫಲ್',
      'nowPlaying': 'ಈಗ ನುಡಿಸುತ್ತಿದೆ',
      'upNext': 'ಮುಂದೆ ಬರುವುದು',
      'clearQueue': 'ತೆರವುಗೊಳಿಸಿ',
      'queueEmpty': 'ಸರತಿ ಸಾಲು ಖಾಲಿಯಾಗಿದೆ.',
      
      // Sleep Timer
      'timerOff': 'ಟೈಮರ್ ಆಫ್',
      'min15': '೧೫ ನಿಮಿಷಗಳು',
      'min30': '೩೦ ನಿಮಿಷಗಳು',
      'min45': '೪೫ ನಿಮಿಷಗಳು',
      'min60': '೬೦ ನಿಮಿಷಗಳು',
      'endOfSong': 'ಹಾಡು ಮುಗಿದ ನಂತರ',
      'timerSetFor': 'ಸ್ಲೀಪ್ ಟೈಮರ್ ಹೊಂದಿಸಲಾಗಿದೆ:',
      'timerCancelled': 'ಟೈಮರ್ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',

      // Favorites & Recents
      'noFavoritesTitle': 'ಇನ್ನೂ ಮೆಚ್ಚಿನ ಹಾಡುಗಳಿಲ್ಲ',
      'noFavoritesSubtitle': 'ಯಾವುದೇ ಭಕ್ತಿಗೀತೆಯನ್ನು ನಿಮ್ಮ ಮೆಚ್ಚಿನ ಪಟ್ಟಿಗೆ ಸೇರಿಸಲು ಹೃದಯ ಐಕಾನ್ ಒತ್ತಿರಿ.',
      'noRecentsTitle': 'ಇತ್ತೀಚೆಗೆ ನುಡಿಸಿದ ಹಾಡುಗಳಿಲ್ಲ',
      'noRecentsSubtitle': 'ನೀವು ಕೇಳಿದ ಹಾಡುಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.',
      
      // Settings
      'settingsTitle': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'languageSetting': 'ಆಪ್ ಭಾಷೆ',
      'themeSetting': 'ಬಣ್ಣ ಮತ್ತು ಥೀಮ್',
      'playbackSetting': 'ಆಡಿಯೋ ಗುಣಮಟ್ಟ',
      'clearCache': 'ಕ್ಯಾಶ್ ತೆರವುಗೊಳಿಸಿ',
      'cacheSize': 'ಉಳಿಸಲಾದ ಡೇಟಾ',
      'clearCacheConfirm': 'ಉಳಿಸಲಾದ ಆಡಿಯೋ ಮತ್ತು ಚಿತ್ರಗಳನ್ನು ತೆರವುಗೊಳಿಸಬೇಕೆ?',
      'cacheCleared': 'ಕ್ಯಾಶ್ ಯಶಸ್ವಿಯಾಗಿ ತೆರವುಗೊಂಡಿದೆ.',
      'clearRecents': 'ಕೇಳಿದ ಇತಿಹಾಸ ತೆರವುಗೊಳಿಸಿ',
      'recentsCleared': 'ಇತಿಹಾಸ ತೆರವುಗೊಂಡಿದೆ.',
      'aboutBhakti': 'ಭಕ್ತಿ ಆಪ್ ಕುರಿತು',
      'privacyPolicy': 'ಗೌಪ್ಯತಾ ನೀತಿ',
      'termsOfService': 'ಬಳಕೆಯ ನಿಯಮಗಳು',
      'contactSupport': 'ಸಂಪರ್ಕಿಸಿ & ಪ್ರತಿಕ್ರಿಯೆ',
      'adminPortal': 'ಅಡ್ಮಿನ್ ಪೋರ್ಟಲ್',
      'version': 'ಆವೃತ್ತಿ',
      
      // Admin Portal
      'adminLogin': 'ಅಡ್ಮಿನ್ ಲಾಗಿನ್',
      'adminLoginSubtitle': 'ಜಾಗತಿಕವಾಗಿ ಭಕ್ತಿಗೀತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
      'username': 'ಬಳಕೆದಾರ ಹೆಸರು / ಇಮೇಲ್',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'login': 'ಲಾಗಿನ್',
      'logout': 'ಲಾಗ್‌ಔಟ್',
      'invalidCredentials': 'ತಪ್ಪಾದ ಮಾಹಿತಿ. ದಯವಿಟ್ಟು ಪರಿಶೀಲಿಸಿ.',
      'adminDashboard': 'ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'totalSongs': 'ಒಟ್ಟು ಹಾಡುಗಳು',
      'publishedSongs': 'ಪ್ರಕಟಿತ',
      'draftSongs': 'ಕರಡುಗಳು',
      'categories': 'ವರ್ಗಗಳು',
      'addSong': '+ ಹೊಸ ಹಾಡು ಸೇರಿಸಿ',
      'editSong': 'ಹಾಡು ತಿದ್ದುಪಡಿ',
      'deleteSong': 'ಹಾಡು ಅಳಿಸಿ',
      'deleteConfirm': 'ಈ ಭಕ್ತಿಗೀತೆಯನ್ನು ಅಳಿಸಲು ಖಚಿತವೇ?',
      'publish': 'ಜಾಗತಿಕವಾಗಿ ಪ್ರಕಟಿಸಿ',
      'saveDraft': 'ಕರಡಾಗಿ ಉಳಿಸಿ',
      'songTitle': 'ಹಾಡಿನ ಶೀರ್ಷಿಕೆ',
      'selectLanguageField': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'selectCategoryField': 'ವರ್ಗ ಆಯ್ಕೆಮಾಡಿ',
      'deityField': 'ದೇವರ ಹೆಸರು',
      'descriptionField': 'ವಿವರಣೆ / ಮಹತ್ವ',
      'artistField': 'ಹಾಡಿದವರು / ರಚನೆ',
      'albumField': 'ಆಲ್ಬಮ್',
      'lyricsField': 'ಸಾಹಿತ್ಯ (ಐಚ್ಛಿಕ)',
      'uploadImage': 'ಚಿತ್ರ ಆಯ್ಕೆಮಾಡಿ (JPG/WebP)',
      'uploadAudio': 'ಆಡಿಯೋ ಆಯ್ಕೆಮಾಡಿ (MP3/M4A)',
      'imageSelected': 'ಚಿತ್ರ ಆಯ್ಕೆಯಾಗಿದೆ',
      'audioSelected': 'ಆಡಿಯೋ ಆಯ್ಕೆಯಾಗಿದೆ',
      'publishingInProgress': 'ಅಪ್‌ಲೋಡ್ ಮತ್ತು ಪ್ರಕಟಿಸಲಾಗುತ್ತಿದೆ...',
      'songSavedSuccess': 'ಹಾಡು ಯಶಸ್ವಿಯಾಗಿ ಪ್ರಕಟವಾಗಿದೆ!',
      'manageCategories': 'ವರ್ಗಗಳ ನಿರ್ವಹಣೆ',
      'syncSampleContent': 'ಮಾದರಿ ಡೇಟಾ ಕ್ಲೌಡ್‌ಗೆ ಸೇರಿಸಿ',

      // Errors & State
      'noInternet': 'ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವಿಲ್ಲ. ಉಳಿಸಿದ ಹಾಡುಗಳು ಲಭ್ಯವಿವೆ.',
      'errorLoadingSongs': 'ಹಾಡುಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ.',
      'errorPlayingAudio': 'ಆಡಿಯೋ ಪ್ಲೇ ಮಾಡಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ.',
      'retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'cancel': 'ರದ್ದು',
      'confirm': 'ಖಚಿತಪಡಿಸಿ',
      'save': 'ಉಳಿಸಿ',
    },

    'hi': {
      // App Branding & General
      'appName': 'भक्ति',
      'appTagline': 'दिव्य संगीत से सुंदर जीवन',
      'spiritualTagline': 'हर किसी के लिए, हर जगह आध्यात्मिकता',
      'heroSpiritualQuote': 'दिव्य संगीत आपके मन को शांति और आनंद से भर दे',
      'universalPrayer': '॥ लोकाः समस्ताः सुखिनो भवन्तु ॥',
      
      // Navigation
      'navHome': 'होम',
      'navSongs': 'लाइब्रेरी',
      'navFavorites': 'पसंदीदा',
      'navSettings': 'सेटिंग्स',
      'navSearch': 'खोजें',
      
      // Home Sections
      'recentlyPlayed': 'हाल ही में सुने गए',
      'popularDevotionals': 'लोकप्रिय भक्ति गीत',
      'recommended': 'आपके लिए अनुशंसित',
      'browseByLanguage': 'भाषा अनुसार देखें',
      'browseByCategory': 'श्रेणियाँ',
      'browseByDeity': 'देवी-देवता',
      'viewAll': 'सभी देखें',
      'playAll': 'सभी बजाएं',
      'clearAll': 'साफ़ करें',
      
      // Language Selection Screen
      'selectLanguage': 'भाषा चुनें',
      'selectLanguageSubtitle': 'एक ऐप • अनेक भाषाएं • एक ही भक्ति',
      'continueButton': 'आगे बढ़ें',
      'kannada': 'ಕನ್ನಡ',
      'english': 'English',
      'hindi': 'हिन्दी',
      'tamil': 'தமிழ்',
      'malayalam': 'മലയാളം',
      
      // Search
      'searchPlaceholder': 'स्तोत्र, भजन, आरती खोजें...',
      'searchHint': 'ललिता, हनुमान, शिव, विष्णु...',
      'noSearchResults': 'कोई भक्ति गीत नहीं मिला।',
      'recentSearches': 'हाल की खोजें',
      
      // Song Details & Library
      'songs': 'भक्ति गीत',
      'allSongs': 'सभी गीत',
      'filterBy': 'फ़िल्टर',
      'lyrics': 'पवित्र बोल / साहित्य',
      'noLyricsAvailable': 'साहित्य शीघ्र उपलब्ध होगा।',
      'deity': 'भगवान',
      'category': 'श्रेणी',
      'duration': 'अवधि',
      'artist': 'गायक / रचयिता',
      
      // Player Controls
      'play': 'चलाएं',
      'pause': 'रोकें',
      'previous': 'पिछला',
      'next': 'अगला',
      'seekForward15': 'आगे 15 से.',
      'seekBackward15': 'पीछे 15 से.',
      'speed': 'गति',
      'sleepTimer': 'स्लीप टाइमर',
      'queue': 'कतार',
      'favorite': 'पसंदीदा',
      'unfavorite': 'हटाएं',
      'addedToFavorites': 'पसंदीदा में जोड़ा गया',
      'removedFromFavorites': 'पसंदीदा से हटाया गया',
      'repeatOff': 'दोहराव बंद',
      'repeatAll': 'सभी दोहराएं',
      'repeatOne': 'एक दोहराएं',
      'shuffle': 'शफ़ल',
      'nowPlaying': 'अभी बज रहा है',
      'upNext': 'अगला गीत',
      'clearQueue': 'कतार साफ़ करें',
      'queueEmpty': 'कतार खाली है।',
      
      // Sleep Timer
      'timerOff': 'टाइमर बंद',
      'min15': '15 मिनट',
      'min30': '30 मिनट',
      'min45': '45 मिनट',
      'min60': '60 मिनट',
      'endOfSong': 'गीत समाप्त होने पर',
      'timerSetFor': 'स्लीप टाइमर सेट किया गया:',
      'timerCancelled': 'टाइमर रद्द कर दिया गया',

      // Favorites & Recents
      'noFavoritesTitle': 'कोई पसंदीदा गीत नहीं',
      'noFavoritesSubtitle': 'अपने पसंदीदा भजनों को यहाँ सहेजने के लिए दिल के निशान को दबाएं।',
      'noRecentsTitle': 'कोई हालिया गीत नहीं',
      'noRecentsSubtitle': 'आपके द्वारा सुने गए भजन यहाँ दिखेंगे।',
      
      // Settings
      'settingsTitle': 'सेटिंग्स',
      'languageSetting': 'ऐप की भाषा',
      'themeSetting': 'थीम और दिखावट',
      'playbackSetting': 'ऑडियो गुणवत्ता',
      'clearCache': 'कैश साफ़ करें',
      'cacheSize': 'संग्रहित मीडिया',
      'clearCacheConfirm': 'कैश किए गए ऑडियो और चित्र साफ़ करें?',
      'cacheCleared': 'कैश सफलतापूर्वक साफ़ किया गया।',
      'clearRecents': 'सुने गए गीतों का इतिहास साफ़ करें',
      'recentsCleared': 'इतिहास साफ़ कर दिया गया।',
      'aboutBhakti': 'भक्ति ऐप के बारे में',
      'privacyPolicy': 'गोपनीयता नीति',
      'termsOfService': 'सेवा की शर्तें',
      'contactSupport': 'संपर्क और सुझाव',
      'adminPortal': 'एडमिन पोर्टल',
      'version': 'संस्करण',
      
      // Admin Portal
      'adminLogin': 'एडमिन लॉगिन',
      'adminLoginSubtitle': 'विश्व स्तर पर भक्ति गीतों का प्रबंधन करें',
      'username': 'उपयोगकर्ता नाम / ईमेल',
      'password': 'पासवर्ड',
      'login': 'लॉगिन',
      'logout': 'लॉगआउट',
      'invalidCredentials': 'गलत विवरण। कृपया पुनः प्रयास करें।',
      'adminDashboard': 'एडमिन डैशबोर्ड',
      'totalSongs': 'कुल गीत',
      'publishedSongs': 'प्रकाशित',
      'draftSongs': 'ड्राफ्ट',
      'categories': 'श्रेणियाँ',
      'addSong': '+ नया गीत जोड़ें',
      'editSong': 'गीत संपादित करें',
      'deleteSong': 'गीत हटाएं',
      'deleteConfirm': 'क्या आप वाकई इस भक्ति गीत को हटाना चाहते हैं?',
      'publish': 'प्रकाशित करें',
      'saveDraft': 'ड्राफ्ट में सहेजें',
      'songTitle': 'गीत का शीर्षक',
      'selectLanguageField': 'भाषा चुनें',
      'selectCategoryField': 'श्रेणी चुनें',
      'deityField': 'देवी / देवता का नाम',
      'descriptionField': 'वर्णन / महत्व',
      'artistField': 'गायक / रचयिता',
      'albumField': 'एल्बम',
      'lyricsField': 'बोल / साहित्य (वैकल्पिक)',
      'uploadImage': 'कवर चित्र चुनें (JPG/WebP)',
      'uploadAudio': 'ऑडियो फ़ाइल चुनें (MP3/M4A)',
      'imageSelected': 'चित्र चुना गया',
      'audioSelected': 'ऑडियो चुना गया',
      'publishingInProgress': 'अपलोड और प्रकाशन जारी है...',
      'songSavedSuccess': 'भक्ति गीत सफलतापूर्वक प्रकाशित हुआ!',
      'manageCategories': 'श्रेणी प्रबंधन',
      'syncSampleContent': 'नमूना डेटा क्लाउड में जोड़ें',

      // Errors & State
      'noInternet': 'इंटरनेट कनेक्शन नहीं है। सहेजे गए गीत उपलब्ध हैं।',
      'errorLoadingSongs': 'गीत लोड करने में असमर्थ। पुनः प्रयास करें।',
      'errorPlayingAudio': 'ऑडियो चलाने में त्रुटि।',
      'retry': 'पुनः प्रयास करें',
      'cancel': 'रद्द करें',
      'confirm': 'पुष्टि करें',
      'save': 'सहेजें',
    },

    'ta': {
      // App Branding & General
      'appName': 'பக்தி',
      'appTagline': 'இனிய வாழ்வுக்கு தெய்வீக இசை',
      'spiritualTagline': 'அனைவருக்கும், எங்கும் ஆன்மீகம்',
      'heroSpiritualQuote': 'தெய்வீக இசை உங்கள் இதயத்தில் அமைதியையும் பக்தியையும் நிரப்பட்டும்',
      'universalPrayer': '॥ லோகாஃ ஸமஸ்தாஃ ஸுகினோ பவந்து ॥',
      
      // Navigation
      'navHome': 'முகப்பு',
      'navSongs': 'பாடல்கள்',
      'navFavorites': 'விருப்பங்கள்',
      'navSettings': 'அமைப்புகள்',
      'navSearch': 'தேடல்',
      
      // Home Sections
      'recentlyPlayed': 'சமீபத்தில் கேட்டவை',
      'popularDevotionals': 'பிரபலமான பக்திப் பாடல்கள்',
      'recommended': 'உங்களுக்கான பரிந்துரைகள்',
      'browseByLanguage': 'மொழி வாரியாக',
      'browseByCategory': 'வகைகள்',
      'browseByDeity': 'தெய்வங்கள்',
      'viewAll': 'அனைத்தும்',
      'playAll': 'அனைத்தையும் இயக்கு',
      'clearAll': 'அழிக்க',
      
      // Language Selection Screen
      'selectLanguage': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'selectLanguageSubtitle': 'ஒரே செயலி • பல மொழிகள் • ஒரே பக்தி',
      'continueButton': 'தொடர்க',
      'kannada': 'ಕನ್ನಡ',
      'english': 'English',
      'hindi': 'हिन्दी',
      'tamil': 'தமிழ்',
      'malayalam': 'മലയാളം',
      
      // Search
      'searchPlaceholder': 'ஸ்தோத்திரங்கள், பாடல்கள், தெய்வங்கள் தேடுக...',
      'searchHint': 'லலிதா, அனுமன், சிவன், விஷ்ணு...',
      'noSearchResults': 'பாடல்கள் எதுவும் கிடைக்கவில்லை.',
      'recentSearches': 'சமீபத்திய தேடல்கள்',
      
      // Song Details & Library
      'songs': 'பக்திப் பாடல்கள்',
      'allSongs': 'அனைத்து பாடல்கள்',
      'filterBy': 'வடிகட்டு',
      'lyrics': 'பாடல் வரிகள்',
      'noLyricsAvailable': 'பாடல் வரிகள் விரைவில் கிடைக்கும்.',
      'deity': 'தெய்வம்',
      'category': 'பிரிவு',
      'duration': 'கால அளவு',
      'artist': 'பாடியவர் / இயற்றியவர்',
      
      // Player Controls
      'play': 'இயக்கு',
      'pause': 'நிறுத்து',
      'previous': 'முந்தையது',
      'next': 'அடுத்தது',
      'seekForward15': 'முன்னோக்கி 15வி',
      'seekBackward15': 'பின்னோக்கி 15வி',
      'speed': 'வேகம்',
      'sleepTimer': 'ஸ்லீப் டைமர்',
      'queue': 'வரிசை',
      'favorite': 'விருப்பம்',
      'unfavorite': 'நீக்கு',
      'addedToFavorites': 'விருப்பங்களில் சேர்க்கப்பட்டது',
      'removedFromFavorites': 'விருப்பங்களிலிருந்து நீக்கப்பட்டது',
      'repeatOff': 'மீண்டும் இயக்கு ஆஃப்',
      'repeatAll': 'அனைத்தையும் மீண்டும் இயக்கு',
      'repeatOne': 'ஒன்றை மீண்டும் இயக்கு',
      'shuffle': 'கலக்கு',
      'nowPlaying': 'இப்போது ஒலிப்பது',
      'upNext': 'அடுத்து வருவது',
      'clearQueue': 'வரிசையை நீக்கு',
      'queueEmpty': 'வரிசை காலியாக உள்ளது.',
      
      // Sleep Timer
      'timerOff': 'டைமர் ஆஃப்',
      'min15': '15 நிமிடங்கள்',
      'min30': '30 நிமிடங்கள்',
      'min45': '45 நிமிடங்கள்',
      'min60': '60 நிமிடங்கள்',
      'endOfSong': 'பாடல் முடிந்ததும்',
      'timerSetFor': 'டைமர் அமைக்கப்பட்டது:',
      'timerCancelled': 'டைமர் ரத்து செய்யப்பட்டது',

      // Favorites & Recents
      'noFavoritesTitle': 'விருப்பப் பாடல்கள் இல்லை',
      'noFavoritesSubtitle': 'பாடல்களை உங்கள் தொகுப்பில் சேர்க்க இதயக் குறியீட்டைத் தட்டவும்.',
      'noRecentsTitle': 'கேட்ட பாடல்கள் இல்லை',
      'noRecentsSubtitle': 'நீங்கள் கேட்ட பாடல்கள் இங்கே தோன்றும்.',
      
      // Settings
      'settingsTitle': 'அமைப்புகள்',
      'languageSetting': 'செயலி மொழி',
      'themeSetting': 'வண்ணம் மற்றும் தோற்றம்',
      'playbackSetting': 'ஒலி தரம்',
      'clearCache': 'கேச் அழிக்க',
      'cacheSize': 'சேமிக்கப்பட்ட தரவு',
      'clearCacheConfirm': 'சேமிக்கப்பட்ட ஆடியோ மற்றும் படங்களை அழிக்கவா?',
      'cacheCleared': 'வெற்றிகரமாக அழிக்கப்பட்டது.',
      'clearRecents': 'வரலாற்றை அழிக்க',
      'recentsCleared': 'வரலாறு அழிக்கப்பட்டது.',
      'aboutBhakti': 'பக்தி செயலி பற்றி',
      'privacyPolicy': 'தனியுரிமைக் கொள்கை',
      'termsOfService': 'பயன்பாட்டு விதிமுறைகள்',
      'contactSupport': 'தொடர்பு & கருத்து',
      'adminPortal': 'நிர்வாகி தளம்',
      'version': 'பதிப்பு',
      
      // Admin Portal
      'adminLogin': 'நிர்வாகி உள்நுழைவு',
      'adminLoginSubtitle': 'பக்திப் பாடல்களை நிர்வகிக்கவும்',
      'username': 'பயனர் பெயர் / மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'login': 'உள்நுழை',
      'logout': 'வெளியேறு',
      'invalidCredentials': 'தவறான தகவல். மீண்டும் முயற்சிக்கவும்.',
      'adminDashboard': 'நிர்வாகக் குழு',
      'totalSongs': 'மொத்த பாடல்கள்',
      'publishedSongs': 'வெளியிடப்பட்டவை',
      'draftSongs': 'வரைவுகள்',
      'categories': 'வகைகள்',
      'addSong': '+ புதிய பாடல் சேர்க்க',
      'editSong': 'பாடல் திருத்து',
      'deleteSong': 'பாடல் நீக்கு',
      'deleteConfirm': 'இந்தப் பாடலை நீக்க விரும்புகிறீர்களா?',
      'publish': 'வெளியிடு',
      'saveDraft': 'வரைவாக சேமி',
      'songTitle': 'பாடல் தலைப்பு',
      'selectLanguageField': 'மொழி தேர்வு',
      'selectCategoryField': 'வகை தேர்வு',
      'deityField': 'தெய்வப் பெயர்',
      'descriptionField': 'விளக்கம்',
      'artistField': 'பாடியவர்',
      'albumField': 'ஆல்பம்',
      'lyricsField': 'பாடல் வரிகள் (விருப்பத்தேர்வு)',
      'uploadImage': 'படம் தேர்வு (JPG/WebP)',
      'uploadAudio': 'ஆடியோ தேர்வு (MP3/M4A)',
      'imageSelected': 'படம் தேர்ந்தெடுக்கப்பட்டது',
      'audioSelected': 'ஆடியோ தேர்ந்தெடுக்கப்பட்டது',
      'publishingInProgress': 'பதிவேற்றப்படுகிறது...',
      'songSavedSuccess': 'பாடல் வெற்றிகரமாக வெளியிடப்பட்டது!',
      'manageCategories': 'வகை மேலாண்மை',
      'syncSampleContent': 'மாதிரி தரவை இணைக்க',

      // Errors & State
      'noInternet': 'இணைய இணைப்பு இல்லை. சேமிக்கப்பட்டவை கிடைக்கின்றன.',
      'errorLoadingSongs': 'ஏற்றுவதில் பிழை.',
      'errorPlayingAudio': 'இயக்குவதில் பிழை.',
      'retry': 'மீண்டும் முயற்சி',
      'cancel': 'ரத்து',
      'confirm': 'உறுதி செய்',
      'save': 'சேமி',
    },

    'ml': {
      // App Branding & General
      'appName': 'ഭക്തി',
      'appTagline': 'ഉത്തമ ജീവിതത്തിനായി ദിവ്യ സംഗീതം',
      'spiritualTagline': 'എല്ലാവർക്കും, എല്ലായിടത്തും ആത്മീയത',
      'heroSpiritualQuote': 'ദിവ്യസംഗീതം നിങ്ങളുടെ മനസ്സിൽ ശാന്തിയും ഭക്തിയും നിറയ്ക്കട്ടെ',
      'universalPrayer': '॥ ലോകാഃ സമസ്താഃ സുഖിനോ ഭവന്തു ॥',
      
      // Navigation
      'navHome': 'ഹോം',
      'navSongs': 'ലൈബ്രറി',
      'navFavorites': 'ഇഷ്ടങ്ങൾ',
      'navSettings': 'ക്രമീകരണങ്ങൾ',
      'navSearch': 'തിരയുക',
      
      // Home Sections
      'recentlyPlayed': 'അടുത്തിടെ കേട്ടവ',
      'popularDevotionals': 'ജനപ്രിയ ഭക്തിഗാനങ്ങൾ',
      'recommended': 'നിങ്ങൾക്കായി തിരഞ്ഞെടുത്തവ',
      'browseByLanguage': 'ഭാഷാടിസ്ഥാനത്തിൽ',
      'browseByCategory': 'വിഭാഗങ്ങൾ',
      'browseByDeity': 'ദേവീദേവന്മാർ',
      'viewAll': 'എല്ലാം കാണുക',
      'playAll': 'എല്ലാം പ്ലേ ചെയ്യുക',
      'clearAll': 'മായ്ക്കുക',
      
      // Language Selection Screen
      'selectLanguage': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'selectLanguageSubtitle': 'ഒരു ആപ്പ് • വിവിധ ഭാഷകൾ • ഒരേ ഭക്തി',
      'continueButton': 'തുടരുക',
      'kannada': 'ಕನ್ನಡ',
      'english': 'English',
      'hindi': 'हिन्दी',
      'tamil': 'தமிழ்',
      'malayalam': 'മലയാളം',
      
      // Search
      'searchPlaceholder': 'സ്തോത്രങ്ങൾ, ഭജനകൾ, ദേവതകൾ തിരയുക...',
      'searchHint': 'ലളിത, ഹനുമാൻ, ശിവൻ, വിഷ്ണു...',
      'noSearchResults': 'ഗാനങ്ങൾ കണ്ടെത്താനായില്ല.',
      'recentSearches': 'അടുത്തിടെ തിരഞ്ഞവ',
      
      // Song Details & Library
      'songs': 'ഭക്തിഗാനങ്ങൾ',
      'allSongs': 'എല്ലാ ഗാനങ്ങളും',
      'filterBy': 'ഫിൽട്ടർ',
      'lyrics': 'വരികൾ',
      'noLyricsAvailable': 'വരികൾ ഉടൻ ലഭ്യമാകും.',
      'deity': 'ദേവത',
      'category': 'വിഭാഗം',
      'duration': 'ദൈർഘ്യം',
      'artist': 'പാടുന്നയാൾ / രചയിതാവ്',
      
      // Player Controls
      'play': 'പ്ലേ ചെയ്യുക',
      'pause': 'പോസ് ചെയ്യുക',
      'previous': 'മുമ്പത്തേത്',
      'next': 'അടുത്തത്',
      'seekForward15': 'മുന്നോട്ട് 15 സെ.',
      'seekBackward15': 'പിന്നോട്ട് 15 സെ.',
      'speed': 'വേഗത',
      'sleepTimer': 'സ്ലീപ് ടൈമർ',
      'queue': 'വരി',
      'favorite': 'ഇഷ്ടം',
      'unfavorite': 'ഒഴിവാക്കുക',
      'addedToFavorites': 'ഇഷ്ടപ്പെട്ടവയിലേക്ക് ചേർത്തു',
      'removedFromFavorites': 'ഇഷ്ടപ്പെട്ടവയിൽ നിന്ന് നീക്കി',
      'repeatOff': 'ആവർത്തനം ഓഫ്',
      'repeatAll': 'എല്ലാം ആവർത്തിക്കുക',
      'repeatOne': 'ഒന്ന് ആവർത്തിക്കുക',
      'shuffle': 'ഷഫിൾ',
      'nowPlaying': 'ഇപ്പോൾ കേൾക്കുന്നത്',
      'upNext': 'അടുത്ത ഗാനം',
      'clearQueue': 'വരി മായ്ക്കുക',
      'queueEmpty': 'വരി ശൂന്യമാണ്.',
      
      // Sleep Timer
      'timerOff': 'ടൈമർ ഓഫ്',
      'min15': '15 മിനിറ്റ്',
      'min30': '30 മിനിറ്റ്',
      'min45': '45 മിനിറ്റ്',
      'min60': '60 മിനിറ്റ്',
      'endOfSong': 'ഗാനം അവസാനിക്കുമ്പോൾ',
      'timerSetFor': 'ടൈമർ നിശ്ചയിച്ചു:',
      'timerCancelled': 'ടൈമർ റദ്ദാക്കി',

      // Favorites & Recents
      'noFavoritesTitle': 'ഇഷ്ടപ്പെട്ട ഗാനങ്ങളില്ല',
      'noFavoritesSubtitle': 'നിങ്ങളുടെ പ്രിയപ്പെട്ട ഗാനങ്ങൾ ചേർക്കാൻ ഹൃദയ ചിഹ്നത്തിൽ സ്പർശിക്കുക.',
      'noRecentsTitle': 'കേട്ട ഗാനങ്ങളില്ല',
      'noRecentsSubtitle': 'നിങ്ങൾ കേട്ട ഗാനങ്ങൾ ഇവിടെ ദൃശ്യമാകും.',
      
      // Settings
      'settingsTitle': 'ക്രമീകരണങ്ങൾ',
      'languageSetting': 'ആപ്പ് ഭാഷ',
      'themeSetting': 'തീം & രൂപഭാവം',
      'playbackSetting': 'ഓഡിയോ ഗുണനിലവാരം',
      'clearCache': 'കാഷെ മായ്ക്കുക',
      'cacheSize': 'സൂക്ഷിച്ച ഡാറ്റ',
      'clearCacheConfirm': 'സൂക്ഷിച്ച ഫയലുകൾ മായ്ക്കാൻ ആഗ്രഹിക്കുന്നുണ്ടോ?',
      'cacheCleared': 'കാഷെ വിജയകരമായി മായ്ച്ചു.',
      'clearRecents': 'കേട്ട ചരിത്രം മായ്ക്കുക',
      'recentsCleared': 'ചരിത്രം മായ്ച്ചു.',
      'aboutBhakti': 'ഭക്തി ആപ്പിനെക്കുറിച്ച്',
      'privacyPolicy': 'സ്വകാര്യതാ നയം',
      'termsOfService': 'ഉപയോഗ നിബന്ധനകൾ',
      'contactSupport': 'ബന്ധപ്പെടുക & പ്രതികരണം',
      'adminPortal': 'അഡ്മിൻ പോർട്ടൽ',
      'version': 'പതിപ്പ്',
      
      // Admin Portal
      'adminLogin': 'അഡ്മിൻ ലോഗിൻ',
      'adminLoginSubtitle': 'ഭക്തിഗാനങ്ങൾ നിയന്ത്രിക്കുക',
      'username': 'യൂസർനെയിം / ഇമെയിൽ',
      'password': 'പാസ്‌വേഡ്',
      'login': 'ലോഗിൻ',
      'logout': 'ലോഗ്ഔട്ട്',
      'invalidCredentials': 'തെറ്റായ വിവരങ്ങൾ. വീണ്ടും ശ്രമിക്കുക.',
      'adminDashboard': 'അഡ്മിൻ ഡാഷ്‌ബോർഡ്',
      'totalSongs': 'ആകെ ഗാനങ്ങൾ',
      'publishedSongs': 'പ്രസിദ്ധീകരിച്ചവ',
      'draftSongs': 'ഡ്രാഫ്റ്റുകൾ',
      'categories': 'വിഭാഗങ്ങൾ',
      'addSong': '+ പുതിയ ഗാനം ചേർക്കുക',
      'editSong': 'ഗാനം എഡിറ്റ് ചെയ്യുക',
      'deleteSong': 'ഗാനം നീക്കം ചെയ്യുക',
      'deleteConfirm': 'ഈ ഗാനം നീക്കം ചെയ്യാൻ ഉറപ്പാണോ?',
      'publish': 'പ്രസിദ്ധീകരിക്കുക',
      'saveDraft': 'ഡ്രാഫ്റ്റായി സൂക്ഷിക്കുക',
      'songTitle': 'ഗാനത്തിന്റെ ശീർഷകം',
      'selectLanguageField': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'selectCategoryField': 'വിഭാഗം തിരഞ്ഞെടുക്കുക',
      'deityField': 'ദേവതയുടെ പേര്',
      'descriptionField': 'വിവരണം',
      'artistField': 'ഗായകൻ / രചയിതാവ്',
      'albumField': 'ആൽബം',
      'lyricsField': 'വരികൾ (ഐച്ഛികം)',
      'uploadImage': 'ചിത്രം തിരഞ്ഞെടുക്കുക (JPG/WebP)',
      'uploadAudio': 'ഓഡിയോ തിരഞ്ഞെടുക്കുക (MP3/M4A)',
      'imageSelected': 'ചിത്രം തിരഞ്ഞെടുത്തു',
      'audioSelected': 'ഓഡിയോ തിരഞ്ഞെടുത്തു',
      'publishingInProgress': 'അപ്‌ലോഡ് ചെയ്യുന്നു...',
      'songSavedSuccess': 'ഗാനം വിജയകരമായി പ്രസിദ്ധീകരിച്ചു!',
      'manageCategories': 'വിഭാഗം കൈകാര്യം ചെയ്യൽ',
      'syncSampleContent': 'മാതൃകാ ഡാറ്റ ക്ലൗഡിലേക്ക് ചേർക്കുക',

      // Errors & State
      'noInternet': 'ഇന്റർനെറ്റ് കണക്ഷൻ ലഭ്യമല്ല. സംരക്ഷിച്ചവ ലഭ്യമാണ്.',
      'errorLoadingSongs': 'ഗാനങ്ങൾ ലഭ്യമാക്കാൻ സാധിക്കുന്നില്ല.',
      'errorPlayingAudio': 'പ്ലേ ചെയ്യാൻ സാധിക്കുന്നില്ല.',
      'retry': 'വീണ്ടും ശ്രമിക്കുക',
      'cancel': 'റദ്ദാക്കുക',
      'confirm': 'സ്ഥിരീകരിക്കുക',
      'save': 'സംരക്ഷിക്കുക',
    },
  };
}
